# Generated by Django 2.1.3 on 2018-12-08 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Microlly', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-id',), 'verbose_name': 'Commentaire', 'verbose_name_plural': 'Commentaires'},
        ),
    ]
